name: Build and Release oneclickvirt

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24.5
        cache-dependency-path: server/go.sum

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Build Go server binaries
      run: |
        cd server
        export GO111MODULE=on
        go mod download
        go mod verify
        export CGO_ENABLED=0
        export LDFLAGS="-s -w -extldflags '-static'"
        
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -ldflags="$LDFLAGS" -o ../build/server-linux-amd64 .
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -ldflags="$LDFLAGS" -o ../build/server-linux-arm64 .
        
        # Windows AMD64
        GOOS=windows GOARCH=amd64 go build -ldflags="$LDFLAGS" -o ../build/server-windows-amd64.exe .
        
        # Windows ARM64
        GOOS=windows GOARCH=arm64 go build -ldflags="$LDFLAGS" -o ../build/server-windows-arm64.exe .

    - name: Build Vue web application
      run: |
        cd web
        rm -rf node_modules package-lock.json
        npm install --no-optional
        npm install @rollup/rollup-linux-x64-gnu --save-dev
        npm run build
        cd dist
        zip -r ../../build/web-dist.zip .
        
    - name: Create build directory
      run: |
        mkdir -p build
        ls -la build/

    - name: Compress binaries
      run: |
        cd build
        tar -czf server-linux-amd64.tar.gz server-linux-amd64
        tar -czf server-linux-arm64.tar.gz server-linux-arm64
        zip server-windows-amd64.zip server-windows-amd64.exe
        zip server-windows-arm64.zip server-windows-arm64.exe
        rm server-linux-amd64 server-linux-arm64 server-windows-amd64.exe server-windows-arm64.exe

    - name: Update install script with new tag
      run: |
        TAG_NAME="v${{ steps.date.outputs.date }}"
        sed -i "s/VERSION=.*/VERSION=\"${TAG_NAME}\"/" install.sh
        
    - name: Commit updated install script
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add install.sh
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: update install script to version v${{ steps.date.outputs.date }}"
          git push
        fi

    - name: Create Release and Upload Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="v${{ steps.date.outputs.date }}"
        RELEASE_BODY="## 自动构建发布 - ${{ steps.date.outputs.date }}
        
        - server-linux-amd64.tar.gz - 后端 Linux AMD64 版本
        - server-linux-arm64.tar.gz - 后端 Linux ARM64 版本  
        - server-windows-amd64.zip - 后端 Windows AMD64 版本
        - server-windows-arm64.zip - 后端 Windows ARM64 版本
        - web-dist.zip - 前端静态文件"
        
        # Create release using GitHub CLI
        gh release create "$TAG_NAME" \
          --title "Release $TAG_NAME" \
          --notes "$RELEASE_BODY" \
          ./build/server-linux-amd64.tar.gz \
          ./build/server-linux-arm64.tar.gz \
          ./build/server-windows-amd64.zip \
          ./build/server-windows-arm64.zip \
          ./build/web-dist.zip
